# SEE https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations
# Or just use https://j-hc.github.io/rvmm-config-gen/

compression-level = 9         # compression level for module zips. between 1 and 9
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
excluded-patches = "'Announcements' 'Premium heading'"
build-mode = "module"
module-prop-name = "rvcmm-yt"
include-stock = true

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
build-mode = "module"
module-prop-name = "rvcmm-ytm"
arch = "arm64-v8a"
include-stock = true

[Messenger]
apkmirror-dlurl = "https://apkmirror.com/apk/facebook-2/messenger/"
uptodown-dlurl = "https://facebook-messenger.en.uptodown.com/android"
excluded-patches = "'Disable switching emoji to sticker'" # last working version is v439 which is 10 months old
build-mode = "module"
module-prop-name = "rvcmm-fb-msg"
arch = "arm64-v8a"
include-stock = true

[Facebook]
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/facebook/"
uptodown-dlurl = "https://facebook.en.uptodown.com/android"
build-mode = "module"
module-prop-name = "rvcmm-fb-main"
arch = "arm64-v8a"
include-stock = true