# SEE https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations
# Or just use https://j-hc.github.io/rvmm-config-gen/

compression-level = 9         # compression level for module zips. between 1 and 9
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

[YouTube]
#apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
build-mode = "module"
included-patches = ""
excluded-patches = "'Announcements' 'Premium heading' 'Theme'"
module-prop-name = "rvcmm-yt"

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
#archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
build-mode = "module"
excluded-patches = ""
module-prop-name = "rvcmm-ytm"
arch = "both"
