# SEE https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

compression-level = 9         # compression level for module zips. between 1 and 9
logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 3             # max number of concurrent building jobs
update-prebuilts = true       # dont touch this
build-mindetach-module = true

# 'predictive-back-gesture' (all apps; only useful for android 13+) and 'compact-header' (for yt music) that got excluded by default
[YouTube]
enabled = true                                                        # add 'enabled = false' key to entries to not build them
build-mode = "module"                                                 # 'both', 'apk' or 'module'
excluded-patches = "debugging"                                        # whitespace seperated list of patches to exclude
included-patches = ""                                                 # whitespace seperated list of patches to include
version = "auto"                                                      # 'auto', 'latest' or a custom one like '17.40.41'
exclusive-patches = false                                             # excludes all patches by default
microg-patch = "microg-support"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "rvcmm-yt"
merge-integrations = true

[Music-arm64]
build-mode = "module"
app-name = "YTMusic"
excluded-patches = "debugging"
included-patches = ""
version = "auto"
microg-patch = "music-microg-support"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "rvcmm-ytm"
arch = "arm64-v8a"

[Music-arm]
build-mode = "module"
app-name = "YTMusic"
excluded-patches = "debugging"
included-patches = ""
version = "auto"
microg-patch = "music-microg-support"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "rvcmm-ytm-v7a"
arch = "arm-v7a"
